version: '3'

services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      # Use backend:5000 for internal Docker network communication
      - VITE_API_URL=http://backend:5000
      - VITE_BACKEND_URL=http://backend:5000
      # Keep localhost URLs for local development reference
      - VITE_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  backend:
    build:
      context: ./MenuGeneratorBarbare
    ports:
      - "5000:5000"
    environment:
      # Fix host binding to use 0.0.0.0 instead of ******* 
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
    volumes:
      - ./MenuGeneratorBarbare:/app
      # Add a named volume for persistent storage
      - ./MenuGeneratorBarbare/build:/app/build
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/getMealList"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge

volumes:
  backend-data:
    driver: local
