version: '3'

services:
  frontend:
    image: ghcr.io/ozraam/tnbarmenuweek-frontend:${TAG:-latest}
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:5000
      - VITE_BACKEND_URL=http://backend:5000
      - VITE_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  backend:
    image: ghcr.io/ozraam/tnbarmenuweek-backend:${TAG:-latest}
    ports:
      - "5000:5000"
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
    volumes:
      - ./build:/app/build
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/getMealList"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge
