version: '3'

services:
  frontend:
    image: ghcr.io/ozraam/tnbarmenuweek-frontend:${TAG:-latest}
    ports:
      - "3000:3000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

networks:
  app-network:
    driver: bridge

